@startmindmap name container_rust_dev_cnt_github_v2
' how the container clone/pull and push files to Github
* rust_dev_cnt\nlinux container
	* clone/pull from and push to Github
		* Github
@endmindmap